---
title: "ANN model"
author: "William Tong"
date: "2024-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading library for ANN 
```{r,cache= TRUE}
library(neuralnet)
library(caret)
```

# Import data
```{r}
cleaned_book <- read.csv("cleaned.csv",stringsAsFactors = TRUE)
cleaned_book$X<- NULL

book_dummy <- as.data.frame(model.matrix(~. -1, data = cleaned_book))
minmax <- function(x) {
  (x - min(x)) / (max(x) - min(x))
}
book_scaled <- as.data.frame(lapply(book_dummy, minmax))
str(book_scaled)
```

## splitting data
```{r,cache= TRUE}
#70:30 split
split_size <- .3
test_size <- split_size*nrow(book_scaled)
set.seed(12345)
test_rows <- sample(1:nrow(book_scaled), test_size)

#make test and train data
book_test <- book_scaled[test_rows, ]
book_train <- book_scaled[-test_rows, ]
summary(book_train)
summary(book_test)
```

## ANN model
```{r,cache= TRUE}
#build an ANN model using nueuralnet
summary(book_train)
m_ann <- neuralnet(booking.status ~., data = book_train, hidden = 3, stepmax = 1e8, lifesign = "full")
summary(m_ann)
```

# Prediction and confusionMatrix
```{r, cache=TRUE}
p_ann<-predict(m_ann, book_test)
p_ann_bin<-ifelse(p_ann>0.5,1,0)
confusionMatrix(as.factor(p_ann_bin), as.factor(book_test$booking.status),positive = "1")
```


# Output CSV file
```{r}
write.csv(p_ann_bin, file = "ANN_output.csv")
```

