---
title: "logistic regression"
author: "Rachel Lewis"
date: "2024-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## libraries needed

```{r}
library(caret)
```


## get and clean data

```{r}
book <- read.csv("cleaned.csv", stringsAsFactors = TRUE)
book$X <- NULL
book$reservation_year <- NULL
book$reservation_day <- as.factor(book$reservation_day)
book$reservation_month <- as.factor(book$reservation_month)
```

## split and train data

```{r, cache = TRUE}
#70:30 split
split_size <- .7
test_size <- split_size*nrow(book)
set.seed(1234)
test_rows <- sample(1:nrow(book), test_size)

#make test and train data
book_test <- book[test_rows, ]
book_train <- book[-test_rows, ]
```

## build model

```{r, cache = TRUE}
#logistic regression model
m_regression <- glm(booking.status ~ . + number.of.adults*number.of.children + number.of.adults*average.price + average.price*number.of.weekend.nights + car.parking.space*number.of.children + number.of.adults*reservation_month + average.price*reservation_month, data = book_train, family = "binomial")

#summary of model
summary(m_regression)

#build step model
step_model <- step(m_regression, direction = "backward")

#summary of step model
summary(step_model)
```

## predict and evaluate model

```{r, cache = TRUE}
#predict model
p_regression <- predict(step_model, book_test, type = "response")
summary(p_regression)

#bin predictions for binary results
p_regression_bin <- ifelse(p_regression > .5, 1, 0)

#evaluate model
confusionMatrix(as.factor(p_regression_bin), as.factor(book_test$booking.status), positive = "1")
```

## export predictions

```{r}
write.csv(p_regression, "logistic_prediction.csv")
```









